language: java

jdk:
- oraclejdk7
- oraclejdk8

branches:
  except:
  - "/^v|d\\d+\\.\\d+\\.\\d+$/"
  - "/^jenkins-jhove-v|d\\d+\\.\\d+\\.\\d+$/"

before_install:
- sudo apt-get install -y realpath

script:
- "./jhove-bbt/scripts/travis-test.sh"

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: 2tPcqxi5BQkomyLYTDk90JrI5iqm9TL5Hc9SklPVemtEUQdDqeEejNjBGIOxQeXxe6Vza/cVEVp8emmb0GQ25k36DeI82kvxWu/dtaXC2B73dr0zFw3IV6VpG9nUcmgNiHrTYDlK5C3QYlkYKDSrAlrBRLA16qiSIe2JpPSClI4=
