language: java

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/

before_install:
  - sudo apt-get install -y realpath

script:
  - ./jhove-bbt/scripts/travis-test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
