language: java

os:
  - linux
  - osx

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

after_script:
 - cp ./auto-vagrant-install.xml ./jhove-installer/target/
 - java -jar ./jhove-installer/target/jhove-installer.jar auto-vagrant-install.xml
